services:
  mariadb: # you should just do a healthcheck in here if using a local database, db-check is intended for remote databases
    image: mariadb:latest
    environment:
      - MARIADB_USER=dbchecker
      - MARIADB_PASSWORD=supersecret
      - MARIADB_DATABASE=mydb
      - MARIADB_ROOT_PASSWORD=evenmoresecret

  db-check:
    image: ghcr.io/jhot21/db-check:latest
    environment:
      - TYPE=mysql # mysql or postgres
      - HOST=mariadb
      - PORT=3306
      - USER=dbchecker
      - PASSWORD=supersecret
      - NAME=mydb
  
  app:
    image: busybox
    depends_on: # add this to your app that depends on a remote database
      db-check:
        condition: service_healthy
    command: echo "hello"
